# Generated by Django 2.1.15 on 2022-04-05 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('audio_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('audio_name', models.CharField(default='', max_length=50)),
                ('path_orig', models.CharField(default='', max_length=100)),
                ('audio_name_processed', models.CharField(max_length=50, null=True)),
                ('path_processed', models.CharField(max_length=100, null=True)),
                ('upload_filename', models.CharField(default='', max_length=50)),
                ('upload_file_count', models.IntegerField(default=1)),
                ('description', models.TextField(default='')),
                ('audio_info', models.CharField(max_length=100, null=True)),
                ('create_by', models.CharField(default='undetect user', max_length=50)),
                ('create_date', models.DateField(default='2022-04-05')),
                ('create_time', models.TimeField(default='13:55:00')),
                ('update_by', models.CharField(default='undetect user', max_length=50)),
                ('update_date', models.DateField(default='2022-04-05')),
                ('update_time', models.TimeField(default='13:55:00')),
            ],
        ),
        migrations.CreateModel(
            name='STTresult',
            fields=[
                ('slice_id', models.IntegerField(primary_key=True, serialize=False)),
                ('start_time', models.FloatField(default=0)),
                ('end_time', models.FloatField(default=0)),
                ('duration', models.FloatField(default=0)),
                ('speaker_label', models.CharField(default='', max_length=20)),
                ('text', models.CharField(max_length=5000, null=True)),
                ('slice_name', models.CharField(default='', max_length=50)),
                ('slice_path', models.CharField(default='', max_length=100)),
                ('create_by', models.CharField(default='undetect user', max_length=50)),
                ('create_date', models.DateField(default='2022-04-05')),
                ('create_time', models.TimeField(default='13:55:00')),
                ('audio_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis.Audio')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(default='123456', max_length=50)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='sttresult',
            unique_together={('audio_id', 'slice_id')},
        ),
    ]
