# Generated by Django 2.1.15 on 2022-04-05 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisSelection',
            fields=[
                ('analysisSelection_id', models.IntegerField(primary_key=True, serialize=False)),
                ('analysis_name', models.CharField(default='None', max_length=50)),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.AlterField(
            model_name='audio',
            name='audio_name_processed',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='audio',
            name='create_time',
            field=models.TimeField(default='15:20:14'),
        ),
        migrations.AlterField(
            model_name='audio',
            name='path_processed',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='audio',
            name='update_time',
            field=models.TimeField(default='15:20:14'),
        ),
        migrations.AlterField(
            model_name='sttresult',
            name='create_time',
            field=models.TimeField(default='15:20:14'),
        ),
    ]
