# Generated by Django 2.1.15 on 2022-04-05 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0003_auto_20220405_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='create_time',
            field=models.TimeField(default='16:06:47'),
        ),
        migrations.AlterField(
            model_name='audio',
            name='update_time',
            field=models.TimeField(default='16:06:47'),
        ),
        migrations.AlterField(
            model_name='sttresult',
            name='create_time',
            field=models.TimeField(default='16:06:47'),
        ),
    ]
