# Generated by Django 3.2.12 on 2022-04-06 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0004_auto_20220405_1606'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='audio',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='sttresult',
            options={'managed': False},
        ),
    ]
