# Generated by Django 3.2.12 on 2022-04-20 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0005_auto_20220406_1018'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='audio',
            options={'managed': True},
        ),
    ]
