# Generated by Django 3.2.12 on 2022-04-20 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0006_alter_audio_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audio',
            name='audio_info',
        ),
        migrations.AddField(
            model_name='audio',
            name='analysis',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='audio',
            name='audio_meta',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='audio',
            name='flg_delete',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='audio',
            name='path_upload',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='audio',
            name='create_date',
            field=models.DateField(default='2022-04-20'),
        ),
        migrations.AlterField(
            model_name='audio',
            name='create_time',
            field=models.TimeField(default='19:48:01'),
        ),
        migrations.AlterField(
            model_name='audio',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='audio',
            name='path_orig',
            field=models.FilePathField(default=''),
        ),
        migrations.AlterField(
            model_name='audio',
            name='update_date',
            field=models.DateField(default='2022-04-20'),
        ),
        migrations.AlterField(
            model_name='audio',
            name='update_time',
            field=models.TimeField(default='19:48:01'),
        ),
    ]
