# Generated by Django 3.2.12 on 2022-04-20 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0008_auto_20220420_1949'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='E:\\EBAC\\Internship\\UOB\\Projects\\uob_web_SIT - 副本\\UOB_SIT\\uob_website\\analysis/audio'),
        ),
        migrations.AlterField(
            model_name='audio',
            name='create_time',
            field=models.TimeField(default='19:54:55'),
        ),
        migrations.AlterField(
            model_name='audio',
            name='path_orig',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='audio',
            name='update_time',
            field=models.TimeField(default='19:54:55'),
        ),
    ]
