# Generated by Django 3.2.12 on 2022-04-20 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0009_auto_20220420_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='E:\\EBAC\\Internship\\UOB\\Projects\\uob_web_SIT - copy\\UOB_SIT\\uob_website\\analysis/audio/'),
        ),
        migrations.AlterField(
            model_name='audio',
            name='create_time',
            field=models.TimeField(default='20:29:03'),
        ),
        migrations.AlterField(
            model_name='audio',
            name='update_time',
            field=models.TimeField(default='20:29:03'),
        ),
    ]
