# Generated by Django 3.2.12 on 2022-04-20 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0011_auto_20220420_2105'),
    ]

    operations = [
        migrations.CreateModel(
            name='Version',
            fields=[
                ('version_id', models.AutoField(primary_key=True, serialize=False)),
                ('version_value', models.CharField(max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='Upload',
        ),
        migrations.RemoveField(
            model_name='audio',
            name='audio_file',
        ),
        migrations.AlterField(
            model_name='audio',
            name='audio_meta',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='audio',
            name='audio_name_processed',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='audio',
            name='create_by',
            field=models.CharField(default='tongtong', max_length=50),
        ),
        migrations.AlterField(
            model_name='audio',
            name='create_time',
            field=models.TimeField(default='22:46:59'),
        ),
        migrations.AlterField(
            model_name='audio',
            name='flg_delete',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='audio',
            name='path_processed',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='audio',
            name='path_upload',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='audio',
            name='update_by',
            field=models.CharField(default='tongtong', max_length=50),
        ),
        migrations.AlterField(
            model_name='audio',
            name='update_time',
            field=models.TimeField(default='22:46:59'),
        ),
    ]
