# Generated by Django 3.2.12 on 2022-04-20 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0012_auto_20220420_2246'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('upload_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('document', models.FileField(blank=True, upload_to='E:\\EBAC\\Internship\\UOB\\Projects\\uob_web_SIT - copy\\UOB_SIT\\uob_website\\analysis/audio/')),
                ('uploaded_by', models.CharField(default='tongtong', max_length=50)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='audio',
            name='create_time',
            field=models.TimeField(default='22:49:11'),
        ),
        migrations.AlterField(
            model_name='audio',
            name='update_time',
            field=models.TimeField(default='22:49:11'),
        ),
    ]
