# Generated by Django 3.2.12 on 2022-04-20 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0014_auto_20220420_2252'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Version',
        ),
        migrations.AlterField(
            model_name='audio',
            name='create_time',
            field=models.TimeField(default='22:55:38'),
        ),
        migrations.AlterField(
            model_name='audio',
            name='update_time',
            field=models.TimeField(default='22:55:38'),
        ),
    ]
