# Generated by Django 3.2.12 on 2022-04-20 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0015_auto_20220420_2255'),
    ]

    operations = [
        migrations.CreateModel(
            name='Version',
            fields=[
                ('version_id', models.AutoField(primary_key=True, serialize=False)),
                ('version_value', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='audio',
            name='create_time',
            field=models.TimeField(default='22:56:14'),
        ),
        migrations.AlterField(
            model_name='audio',
            name='update_time',
            field=models.TimeField(default='22:56:14'),
        ),
    ]
