# Generated by Django 3.2.12 on 2022-04-20 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0016_auto_20220420_2256'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Version',
        ),
        migrations.AlterField(
            model_name='audio',
            name='create_time',
            field=models.TimeField(default='22:57:00'),
        ),
        migrations.AlterField(
            model_name='audio',
            name='update_time',
            field=models.TimeField(default='22:57:00'),
        ),
    ]
