# Generated by Django 3.2.12 on 2022-04-20 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0018_auto_20220420_2257'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='version',
            options={'managed': False},
        ),
        migrations.AlterField(
            model_name='audio',
            name='create_time',
            field=models.TimeField(default='22:58:28'),
        ),
        migrations.AlterField(
            model_name='audio',
            name='update_time',
            field=models.TimeField(default='22:58:28'),
        ),
    ]
