# Generated by Django 3.2.12 on 2022-04-20 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0021_auto_20220420_2305'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Version',
        ),
        migrations.AlterField(
            model_name='audio',
            name='create_time',
            field=models.TimeField(default='23:05:55'),
        ),
        migrations.AlterField(
            model_name='audio',
            name='update_time',
            field=models.TimeField(default='23:05:55'),
        ),
    ]
