# Generated by Django 3.2.12 on 2022-04-20 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0023_auto_20220420_2306'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='version',
            options={'managed': False},
        ),
        migrations.AlterField(
            model_name='audio',
            name='create_time',
            field=models.TimeField(default='23:07:47'),
        ),
        migrations.AlterField(
            model_name='audio',
            name='update_time',
            field=models.TimeField(default='23:07:47'),
        ),
    ]
