# Generated by Django 3.2.12 on 2022-04-20 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0025_auto_20220420_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='create_time',
            field=models.TimeField(default='23:47:33'),
        ),
        migrations.AlterField(
            model_name='audio',
            name='update_time',
            field=models.TimeField(default='23:47:33'),
        ),
        migrations.AlterField(
            model_name='upload',
            name='upload_id',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
