# Generated by Django 3.2.12 on 2022-04-20 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0026_auto_20220420_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='create_date',
            field=models.DateField(default='2022-04-21'),
        ),
        migrations.AlterField(
            model_name='audio',
            name='create_time',
            field=models.TimeField(default='00:23:33'),
        ),
        migrations.AlterField(
            model_name='audio',
            name='update_date',
            field=models.DateField(default='2022-04-21'),
        ),
        migrations.AlterField(
            model_name='audio',
            name='update_time',
            field=models.TimeField(default='00:23:33'),
        ),
        migrations.AlterField(
            model_name='upload',
            name='uploaded_at',
            field=models.DateTimeField(default=1650471813.1426666),
        ),
    ]
