# Generated by Django 3.2.12 on 2022-04-20 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0027_auto_20220421_0023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='create_time',
            field=models.TimeField(default='00:24:47'),
        ),
        migrations.AlterField(
            model_name='audio',
            name='update_time',
            field=models.TimeField(default='00:24:47'),
        ),
        migrations.AlterField(
            model_name='upload',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
