# Generated by Django 3.2.12 on 2022-04-20 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0028_auto_20220421_0024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='create_time',
            field=models.TimeField(default='00:27:11'),
        ),
        migrations.AlterField(
            model_name='audio',
            name='update_time',
            field=models.TimeField(default='00:27:11'),
        ),
        migrations.AlterField(
            model_name='upload',
            name='uploaded_at',
            field=models.DateTimeField(default=1650472031.5510898),
        ),
    ]
