# Generated by Django 3.2.12 on 2022-04-21 17:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0029_auto_20220421_0027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='create_date',
            field=models.DateField(default='2022-04-22'),
        ),
        migrations.AlterField(
            model_name='audio',
            name='create_time',
            field=models.TimeField(default='01:34:13'),
        ),
        migrations.AlterField(
            model_name='audio',
            name='update_date',
            field=models.DateField(default='2022-04-22'),
        ),
        migrations.AlterField(
            model_name='audio',
            name='update_time',
            field=models.TimeField(default='01:34:13'),
        ),
        migrations.AlterField(
            model_name='upload',
            name='uploaded_at',
            field=models.DateTimeField(default=datetime.date(2022, 4, 22)),
        ),
    ]
