# Generated by Django 3.2.12 on 2022-04-26 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0031_auto_20220426_1837'),
    ]

    operations = [
        migrations.CreateModel(
            name='STTresult',
            fields=[
                ('slice_id', models.IntegerField(primary_key=True, serialize=False)),
                ('start_time', models.FloatField(default=0)),
                ('end_time', models.FloatField(default=0)),
                ('duration', models.FloatField(default=0)),
                ('speaker_label', models.CharField(default='', max_length=20)),
                ('text', models.CharField(blank=True, max_length=5000, null=True)),
                ('slice_name', models.CharField(default='', max_length=50)),
                ('slice_path', models.CharField(default='', max_length=100)),
                ('create_by', models.CharField(default='tongtong', max_length=50)),
                ('create_date', models.DateField(default='2022-04-26')),
                ('create_time', models.TimeField(default='18:42:43')),
            ],
            options={
                'managed': False,
            },
        ),
    ]
