# Generated by Django 3.2.12 on 2022-04-26 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0032_sttresult'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sttresult',
            options={'managed': True},
        ),
    ]
