# Generated by Django 3.2.12 on 2022-04-26 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0033_alter_sttresult_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sttresult',
            options={'managed': False},
        ),
    ]
