# Generated by Django 3.2.12 on 2022-04-26 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0035_alter_upload_uploaded_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='STTresult',
        ),
    ]
