# Generated by Django 3.2.12 on 2022-05-10 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0037_sttresult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='document',
            field=models.FileField(blank=True, upload_to='D:/EBAC/Internship/UOB/Projects/uob_web_SIT-copy/audio/'),
        ),
    ]
