# Generated by Django 3.2.12 on 2022-05-26 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0038_alter_upload_document'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
