# Generated by Django 3.2.12 on 2022-06-18 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0039_delete_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='upload',
            options={'managed': False},
        ),
        migrations.CreateModel(
            name='PersonalInfo',
            fields=[
                ('audio_slice_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('audio_id', models.CharField(max_length=30)),
                ('slice_id', models.IntegerField()),
                ('is_kyc', models.CharField(max_length=5)),
                ('is_pii', models.CharField(max_length=5)),
            ],
            options={
                'managed': True,
                'unique_together': {('audio_id', 'slice_id')},
            },
        ),
    ]
