# Generated by Django 3.2.12 on 2022-06-18 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0040_auto_20220618_1300'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personalinfo',
            options={'managed': False},
        ),
    ]
