# Generated by Django 3.2.12 on 2022-06-29 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0041_alter_personalinfo_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Version',
        ),
    ]
